// Information 板块的真实数据源清单。
// 全部是免费、不需要 API Key 的公开 RSS/Atom 源。
// 想增加/替换来源：在这个数组里加一行即可，不用改其他代码。
export const FEEDS = [
  // ── Preprint Servers ──────────────────────────────────────────────────────
  { url: "https://rss.arxiv.org/rss/cs.AI",          name: "arXiv cs.AI",                sourceType: "preprint" },
  { url: "https://rss.arxiv.org/rss/cs.LG",          name: "arXiv cs.LG",                sourceType: "preprint" },
  { url: "https://rss.arxiv.org/rss/cs.CL",          name: "arXiv cs.CL",                sourceType: "preprint" },
  { url: "https://rss.arxiv.org/rss/cs.RO",          name: "arXiv cs.RO (Robotics)",     sourceType: "preprint" },
  { url: "https://rss.arxiv.org/rss/cs.CV",          name: "arXiv cs.CV (Vision)",       sourceType: "preprint" },
  { url: "https://rss.arxiv.org/rss/cs.NE",          name: "arXiv cs.NE (Neural Evol.)", sourceType: "preprint" },
  { url: "https://rss.arxiv.org/rss/cs.DC",          name: "arXiv cs.DC (Distributed)",  sourceType: "preprint" },
  { url: "https://rss.arxiv.org/rss/stat.ML",        name: "arXiv stat.ML",              sourceType: "preprint" },
  { url: "https://rss.arxiv.org/rss/cs.HC",          name: "arXiv cs.HC (HCI & AI)",     sourceType: "preprint" },
  { url: "https://rss.arxiv.org/rss/eess.SP",        name: "arXiv eess.SP (Signal Proc.)",sourceType: "preprint" },

  // ── Government / Research Institutions ───────────────────────────────────
  { url: "https://news.mit.edu/rss/topic/artificial-intelligence2",
    name: "MIT News · AI",                 sourceType: "gov-research" },
  { url: "https://hai.stanford.edu/news/rss.xml",
    name: "Stanford HAI",                  sourceType: "gov-research" },
  { url: "https://spectrum.ieee.org/feeds/feed.rss",
    name: "IEEE Spectrum",                 sourceType: "gov-research" },
  { url: "https://allenai.org/blog-rss.xml",
    name: "Allen Institute for AI",        sourceType: "gov-research" },
  { url: "https://www.nist.gov/blogs/cybersecurity-insights/rss.xml",
    name: "NIST · AI & Cybersecurity",    sourceType: "gov-research" },
  { url: "https://cset.georgetown.edu/feed/",
    name: "Georgetown CSET",               sourceType: "gov-research" },
  { url: "https://bair.berkeley.edu/blog/feed.xml",
    name: "Berkeley AI Research (BAIR)",   sourceType: "gov-research" },
  { url: "https://ai.stanford.edu/blog/feed.xml",
    name: "Stanford AI Lab Blog",          sourceType: "gov-research" },

  // ── Industry Tech Labs ────────────────────────────────────────────────────
  { url: "https://blogs.nvidia.com/feed/",
    name: "NVIDIA Blog",                   sourceType: "industry-lab" },
  { url: "https://www.microsoft.com/en-us/research/feed/",
    name: "Microsoft Research",            sourceType: "industry-lab" },
  { url: "https://openai.com/blog/rss.xml",
    name: "OpenAI Blog",                   sourceType: "industry-lab" },
  { url: "https://deepmind.google/blog/rss.xml",
    name: "Google DeepMind Blog",          sourceType: "industry-lab" },
  { url: "https://blog.research.google/feeds/posts/default",
    name: "Google Research Blog",          sourceType: "industry-lab" },
  { url: "https://ai.meta.com/blog/rss/",
    name: "Meta AI Blog",                  sourceType: "industry-lab" },
  { url: "https://machinelearning.apple.com/rss.xml",
    name: "Apple Machine Learning",        sourceType: "industry-lab" },
  { url: "https://www.amazon.science/index.rss",
    name: "Amazon Science",                sourceType: "industry-lab" },
  { url: "https://www.anthropic.com/rss.xml",
    name: "Anthropic Blog",                sourceType: "industry-lab" },
  { url: "https://mistral.ai/news/rss",
    name: "Mistral AI News",               sourceType: "industry-lab" },
  { url: "https://stability.ai/news?format=rss",
    name: "Stability AI News",             sourceType: "industry-lab" },
  { url: "https://blog.salesforceairesearch.com/rss/",
    name: "Salesforce AI Research",        sourceType: "industry-lab" },
  { url: "https://engineering.fb.com/category/ml-applications/feed/",
    name: "Meta Engineering · ML",        sourceType: "industry-lab" },
  { url: "https://blogs.microsoft.com/ai/feed/",
    name: "Microsoft AI Blog",             sourceType: "industry-lab" },

  // ── Developer Communities ─────────────────────────────────────────────────
  { url: "https://huggingface.co/blog/feed.xml",
    name: "Hugging Face Blog",             sourceType: "dev-community" },
  { url: "https://hnrss.org/newest?q=AI&points=50",
    name: "Hacker News (AI, 50+ pts)",     sourceType: "dev-community" },
  { url: "https://hnrss.org/newest?q=machine+learning&points=30",
    name: "Hacker News (ML, 30+ pts)",     sourceType: "dev-community" },
  { url: "https://hnrss.org/newest?q=LLM&points=30",
    name: "Hacker News (LLM, 30+ pts)",    sourceType: "dev-community" },
  { url: "https://dev.to/feed/tag/machinelearning",
    name: "Dev.to · Machine Learning",     sourceType: "dev-community" },
  { url: "https://dev.to/feed/tag/ai",
    name: "Dev.to · AI",                   sourceType: "dev-community" },
  { url: "https://dev.to/feed/tag/deeplearning",
    name: "Dev.to · Deep Learning",        sourceType: "dev-community" },
  { url: "https://dev.to/feed/tag/llm",
    name: "Dev.to · LLM",                  sourceType: "dev-community" },
  { url: "https://paperswithcode.com/latest/rss",
    name: "Papers with Code",              sourceType: "dev-community" },
  { url: "https://gradientflow.com/feed/",
    name: "Gradient Flow",                 sourceType: "dev-community" },
  { url: "https://towardsdatascience.com/feed",
    name: "Towards Data Science",          sourceType: "dev-community" },
  { url: "https://neptune.ai/blog/feed",
    name: "Neptune.ai Blog",               sourceType: "dev-community" },

  // ── Venture Capital / Business Media ─────────────────────────────────────
  { url: "https://techcrunch.com/category/artificial-intelligence/feed/",
    name: "TechCrunch · AI",               sourceType: "vc-media" },
  { url: "https://techcrunch.com/category/fintech/feed/",
    name: "TechCrunch · Fintech",          sourceType: "vc-media" },
  { url: "https://venturebeat.com/category/ai/feed/",
    name: "VentureBeat · AI",              sourceType: "vc-media" },
  { url: "https://www.wired.com/feed/category/artificial-intelligence/latest/rss",
    name: "WIRED · AI",                    sourceType: "vc-media" },
  { url: "https://www.technologyreview.com/feed/",
    name: "MIT Technology Review",         sourceType: "vc-media" },
  { url: "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml",
    name: "The Verge · AI",               sourceType: "vc-media" },
  { url: "https://www.businessinsider.com/sai/rss",
    name: "Business Insider · Tech",      sourceType: "vc-media" },
  { url: "https://fortune.com/feed/fortune-feeds/?id=3230629",
    name: "Fortune · Technology",         sourceType: "vc-media" },
];

// 实习/内推板块：社区持续维护、每天自动更新的开源实习清单（GitHub raw JSON，免 key）。
export const INTERNSHIP_SOURCES = [
  {
    url: "https://raw.githubusercontent.com/SimplifyJobs/Summer2026-Internships/dev/.github/scripts/listings.json",
    label: "SimplifyJobs / Summer2026-Internships",
  },
  {
    url: "https://raw.githubusercontent.com/vanshb03/Summer2027-Internships/dev/.github/scripts/listings.json",
    label: "vanshb03 / Summer2027-Internships",
  },
];

export const AI_KEYWORDS = [
  "ai", "machine learning", "ml ", " ml", "deep learning", "data scien", "research",
  "nlp", "computer vision", "llm", "artificial intelligence",
];
